#!/usr/bin/env python3
"""Step 3 — K-fold cross-validation training with nnU-Net v2.

Features
--------
- 5-fold CV (configurable via NUM_FOLDS / --num-folds)
- nnU-Net auto-splits (generated by nnUNetv2_plan_and_preprocess)
- Real-time CSV logging of train_loss / val_loss / val_Dice per epoch
- Early stopping via ``nnUNetTrainerEarlyStopping`` (in-process) and
  subprocess-level monitor (kills the process if patience exceeded)
- Reproducibility: seeds Python / NumPy / PyTorch / CUDA via $NNUNET_SEED
- GPU selection via $CUDA_VISIBLE_DEVICES
- Per-fold checkpoints: best_model.pth + last_model.pth
- Global best checkpoint across all folds
- MLflow + CSV experiment tracking

Environment variables (set in .env)
------------------------------------
    nnUNet_raw / nnUNet_preprocessed / nnUNet_results   (required)
    DATASET_ID              Dataset integer ID
    NNUNET_CONFIGURATION    e.g. 3d_fullres (default)
    NUM_FOLDS               Number of CV folds (default: 5)
    CUDA_VISIBLE_DEVICES    GPU index/es (default: 0)
    EXPERIMENT_NAME         MLflow experiment label
    MLFLOW_TRACKING_URI     MLflow backend URI

Usage
-----
::

    # Train all 5 folds with default settings
    python scripts/03_train.py

    # Train specific folds
    python scripts/03_train.py --folds 0 1

    # Resume interrupted training
    python scripts/03_train.py --continue-training

    # Disable early stopping
    python scripts/03_train.py --es-patience 0

    # Standard nnUNetTrainer (no in-process early stopping)
    python scripts/03_train.py --trainer nnUNetTrainer

    # Custom seed
    python scripts/03_train.py --seed 1337

    # Specific GPU
    CUDA_VISIBLE_DEVICES=1 python scripts/03_train.py
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.utils.env_utils import load_env, get_env, get_path_env, dataset_folder_name, nnunet_env
from src.utils.logging_utils import get_logger
from src.training.cross_validation import CrossValidationOrchestrator
from src.training.reproducibility import cuda_info, set_global_seed


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )

    # ── Fold selection ────────────────────────────────────────────────────────
    p.add_argument(
        "--folds",
        type=int,
        nargs="+",
        default=None,
        metavar="N",
        help="Fold indices to train (default: all). E.g. --folds 0 1 2",
    )
    p.add_argument(
        "--num-folds",
        type=int,
        default=None,
        metavar="N",
        help="Total number of folds (default: $NUM_FOLDS or 5)",
    )

    # ── nnU-Net identifiers ───────────────────────────────────────────────────
    p.add_argument("--configuration", default=None, help="nnU-Net configuration override")
    p.add_argument(
        "--trainer",
        default="nnUNetTrainerEarlyStopping",
        help="nnU-Net trainer class (default: nnUNetTrainerEarlyStopping)",
    )
    p.add_argument("--plans", default="nnUNetPlans", help="Plans identifier")

    # ── Training control ──────────────────────────────────────────────────────
    p.add_argument(
        "--continue-training",
        action="store_true",
        help="Resume from existing checkpoint (passes --c to nnUNetv2_train)",
    )

    # ── Reproducibility ───────────────────────────────────────────────────────
    p.add_argument(
        "--seed",
        type=int,
        default=None,
        metavar="INT",
        help="Global random seed (default: $NNUNET_SEED or 42)",
    )

    # ── Early stopping ────────────────────────────────────────────────────────
    p.add_argument(
        "--es-patience",
        type=int,
        default=None,
        metavar="EPOCHS",
        help="Early stopping patience in epochs (0 = disable, default: $ES_PATIENCE or 50)",
    )
    p.add_argument(
        "--es-min-delta",
        type=float,
        default=None,
        metavar="FLOAT",
        help="Minimum Dice improvement to reset patience (default: $ES_MIN_DELTA or 1e-4)",
    )
    p.add_argument(
        "--es-warmup",
        type=int,
        default=None,
        metavar="EPOCHS",
        help="Warmup epochs before early stopping activates (default: $ES_WARMUP or 50)",
    )

    # ── Output dirs ───────────────────────────────────────────────────────────
    p.add_argument("--metrics-dir", default="metrics", help="Metrics CSV output directory")
    p.add_argument("--checkpoints-dir", default="checkpoints", help="Checkpoint archive directory")
    p.add_argument("--log-dir", default="logs", help="Log file directory")

    return p.parse_args()


def _validate_prereqs(log) -> bool:
    """Check that preprocessing has been run before training."""
    try:
        env = nnunet_env()
    except KeyError as exc:
        log.error(f"Missing required env var: {exc}")
        return False

    preprocessed = Path(env["nnUNet_preprocessed"]) / dataset_folder_name()
    if not preprocessed.exists():
        log.error(
            f"Preprocessed directory not found: {preprocessed}\n"
            "Run scripts/02_preprocess.py first."
        )
        return False

    splits_file = preprocessed / "splits_final.json"
    if not splits_file.exists():
        log.error(
            f"splits_final.json not found: {splits_file}\n"
            "Run scripts/02_preprocess.py first."
        )
        return False

    with splits_file.open() as fh:
        splits = json.load(fh)
    log.info(f"Found {len(splits)}-fold splits in {splits_file.name}")
    return True


def main() -> None:
    load_env()
    args = parse_args()
    log = get_logger(name="03_train", log_dir=args.log_dir)

    # ── Resolve all parameters (CLI > env > default) ──────────────────────────
    seed = args.seed if args.seed is not None else int(get_env("NNUNET_SEED", default="42"))
    num_folds = args.num_folds or int(get_env("NUM_FOLDS", default="5"))
    config = args.configuration or get_env("NNUNET_CONFIGURATION", default="3d_fullres")
    es_patience = (
        args.es_patience
        if args.es_patience is not None
        else int(get_env("ES_PATIENCE", default="50"))
    )
    es_min_delta = (
        args.es_min_delta
        if args.es_min_delta is not None
        else float(get_env("ES_MIN_DELTA", default="1e-4"))
    )
    es_warmup = (
        args.es_warmup
        if args.es_warmup is not None
        else int(get_env("ES_WARMUP", default="50"))
    )

    # ── Apply seed in orchestrator process too ─────────────────────────────────
    set_global_seed(seed)

    # ── GPU / CUDA info ────────────────────────────────────────────────────────
    gpu = cuda_info()
    cuda_dev = get_env("CUDA_VISIBLE_DEVICES", default="0")

    log.info("=" * 64)
    log.info("  Step 3: K-Fold Cross-Validation Training")
    log.info("=" * 64)
    log.info(f"  Configuration  : {config}")
    log.info(f"  Trainer class  : {args.trainer}")
    log.info(f"  Plans          : {args.plans}")
    log.info(f"  Num folds      : {num_folds}")
    log.info(f"  Folds selected : {args.folds or list(range(num_folds))}")
    log.info(f"  Continue       : {args.continue_training}")
    log.info(f"  Seed           : {seed}")
    log.info(f"  CUDA devices   : {cuda_dev}")
    log.info(f"  GPU available  : {gpu.get('cuda_available')}  {gpu.get('device_name', '')}")
    log.info(f"  Early stopping : patience={es_patience}  min_delta={es_min_delta}  warmup={es_warmup}")
    log.info(f"  Metrics dir    : {args.metrics_dir}")
    log.info(f"  Checkpoints dir: {args.checkpoints_dir}")
    log.info("=" * 64)

    # ── Pre-flight checks ──────────────────────────────────────────────────────
    if not _validate_prereqs(log):
        sys.exit(1)

    # ── Run ────────────────────────────────────────────────────────────────────
    orchestrator = CrossValidationOrchestrator(
        num_folds=num_folds,
        configuration=config,
        trainer_class=args.trainer,
        plans_identifier=args.plans,
        continue_training=args.continue_training,
        seed=seed,
        es_patience=es_patience,
        es_min_delta=es_min_delta,
        es_warmup=es_warmup,
        metrics_dir=args.metrics_dir,
        checkpoints_dir=args.checkpoints_dir,
    )

    results = orchestrator.run(folds=args.folds)

    # ── Exit code ──────────────────────────────────────────────────────────────
    failed = [f for f, rc in results.items() if rc != 0]
    if failed:
        log.error(f"Failed folds: {failed}")
        sys.exit(1)

    log.success("All folds completed successfully.")

    # ── Print checkpoint manifest ──────────────────────────────────────────────
    ckpt_manifest = Path(args.checkpoints_dir) / "manifest.json"
    if ckpt_manifest.exists():
        with ckpt_manifest.open() as fh:
            m = json.load(fh)
        log.info(
            f"\nCheckpoint manifest:\n"
            f"  Global best fold : {m.get('best_fold')}\n"
            f"  Global best Dice : {m.get('best_val_dice')}\n"
            f"  Location         : {args.checkpoints_dir}/global_best/best_model.pth"
        )


if __name__ == "__main__":
    main()
